### ISSUE TITLE
fix:  issues running with docker

### ISSUE THREAD

**Issue by Alch-Emi** [harmony-development/scherzo#157]
howdy!  i'm trying to set up scherzo with docker on my VPS, but i'm running into some issues.

using `yusdacra/scherzo:latest` (`76e317e` at writing), i'm getting the error:

```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

building the docker image from source produces the same result (commit `f17da7c`), as does running with docker compose or the docker command provided in the README.

i'm running docker-compose version 1.25.0 with Docker version 20.10.12, build e91ed57 on Ubuntu 20.04.3 LTS.  My docker compose snippet is:

```yaml
version: "3"
services:
  scherzo:
    image: yusdacra/scherzo:latest
    volumes:
      - /data/scherzo/db:/srv/scherzo/db
      - /data/scherzo/media:/srv/scherzo/media
  ...
```

any advice is appreciated.  thank you very much!
